trigger:
  - main
  - feature/*
pool:
  vmImage: ubuntu-latest
stages:
  # Continuous Integration Process
  - stage: CI
    jobs:
      - job: BuildAndPushDocker
        workspace:
          clean: all

        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "weightapprepo.azurecr.io"
              repository: "weightapprepo"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"

        # Continuous Deployment Process for Staging Environment
  - stage: DeployToStaging
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: staging
        displayName: Deploy to Staging
        environment:
          name: staging
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: CmdLine@2
                  inputs:
                    script: |
                      sudo apt update
                      sudo apt upgrade -y
                      sudo apt install docker.io -y
                      sudo chmod 666 /var/run/docker.sock
                - task: Docker@2
                  inputs:
                    containerRegistry: "weightapprepo.azurecr.io"
                    command: "login"

                - task: CmdLine@2
                  inputs:
                    script: "docker pull weightapprepo.azurecr.io/weightapprepo:$(tag)"

                - task: CmdLine@2
                  inputs:
                    script: "docker run -p -d 8080:8080 weightapprepo.azurecr.io/weightapprepo:latest"
