trigger:
  - main
  - feature/*

pool:
  vmImage: ubuntu-latest
stages:
  # Continuous Integration Process
  - stage: prepare_CI
    jobs:
      - job: BuildAndPushDocker
        workspace:
          clean: all

        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "weightapprepo.azurecr.io"
              repository: "weightapprepo"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: $(Build.BuildId)

  - stage: CI
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    variables:
      - group: staging
    jobs:
      - deployment: staging
        displayName: Deploy to Staging
        environment:
          name: staging
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: CmdLine@2
                  inputs:
                    script: |
                      sudo apt update
                      sudo apt upgrade -y
                      sudo apt install docker.io -y
                      sudo chmod 666 /var/run/docker.sock
                - task: Docker@2
                  inputs:
                    containerRegistry: "weightapprepo.azurecr.io"
                    command: "login"

                - task: CmdLine@2
                  inputs:
                    script: |
                      docker rmi -f $(docker images -a -q)
                      docker rm -f $(docker ps -a -q)
                      docker pull weightapprepo.azurecr.io/weightapprepo:$(Build.BuildId)
                  displayName: clean and repull docker image

                - task: CmdLine@2
                  inputs:
                    script: |
                      docker run -d --restart unless-stopped -p 8080:8080 -e PORT=$(PORT) --name weightapp weightapprepo.azurecr.io/weightapprepo:$(Build.BuildId)
                  displayName: docker run and restart
