trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
pool:
  name: Default
  vmImage: "terraformAgent"

stages:
# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
      - template: ci.yml



# Continuous Deployment Process for Production Environment
- stage: DeployToProd
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: production
    displayName: Deploy to Production
    environment:
      name: production
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
      - template: cd.yml
