
trigger:
- main

pool:
  vmImage: "ubuntu-latest"
  
stages :
# - stage: Build
#   jobs:
#   - deployment: Build
#     displayName: Build Web App
#     pool:
#       vmImage: 'ubuntu-latest'

#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: DockerInstaller@0
#             inputs:
#               dockerVersion: '17.09.0-ce'
#           - task: Bash@3
#             inputs:
#               targetType: 'inline'
#               script: 'ls'
#           - task: Docker@2
#             inputs:
#               containerRegistry: 'weightapprepo.azurecr.io'
#               repository: 'weightapp'
#               command: 'buildAndPush'
#               Dockerfile: 'dockerfiles/Dockerfile'




- stage: deploy
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment: 
      name: staging
      resourceType: VirtualMachine
      tags: staging # only deploy to virtual machines with this tag
    strategy:
      runOnce:
        deploy:   
            steps:
            - task: DockerInstaller@0
              inputs:
                dockerVersion: '17.09.0-ce'
            
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  uname -a
                  
                  docker --version
            - task: Docker@2
              inputs:
                containerRegistry: 'weightapprepo.azurecr.io'
                command: 'login'

            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  docker pull weightapprepo.azurecr.io/weightapp:294
                  
                  
                  docker images