trigger:
  - master
  - feature/*

pool:
  vmImage: ubuntu-latest
stages:
  # Continuous Integration Process
  - stage: prepare_CI
    jobs:
      - job: CI
        workspace:
          clean: all

        steps:
          - task: Docker@2 ## step 1 connecting to acr
            inputs:
              containerRegistry: "weightapprepo.azurecr.io"
              command: "login"
          - task: Docker@2
            inputs:
              containerRegistry: "weightapprepo.azurecr.io"
              repository: "weightapprepo"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: $(Build.BuildId)

  - stage: CI_to_staging
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    variables:
      - group: staging
    jobs:
      - deployment: staging
        displayName: Deploy to Staging
        environment:
          name: staging
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: CmdLine@2
                  inputs:
                    script: |
                      sudo apt update
                      sudo apt upgrade -y
                      sudo apt install docker.io -y
                      sudo chmod 666 /var/run/docker.sock
                - task: Docker@2
                  inputs:
                    containerRegistry: "weightapprepo.azurecr.io"
                    command: "login"

                - task: CmdLine@2
                  inputs:
                    script: |
                      docker rmi -f $(docker images -a -q)
                      docker rm -f $(docker ps -a -q)
                      # security bug fix below:
                      docker pull weightapprepo.azurecr.io/weightapprepo:$(Build.BuildId)
                  displayName: clean and repull docker image

                - task: CmdLine@2
                  inputs:
                    script: |
                      docker run -d -p 8080:8080  --restart=always --name weightapp -e HOST=$(HOST) -e PORT=$(PORT) -e PGHOST=$(PGHOST) -e PGUSERNAME=$(PGUSERNAME) -e PGDATABASE=$(PGDBNAME) -e PGPASSWORD=$(PGPASS) -e COOKIE_ENCRYPT_PWD=$(COOKIE_ENCRYPT_PWD) -e OKTA_ORG_URL=$(OKTAURL) -e OKTA_CLIENT_ID=$(OKTACLIENT) -e OKTA_CLIENT_SECRET=$(OKTASECRET) weightapprepo.azurecr.io/weightapprepo:$(Build.BuildId)
                  displayName: docker run and restart
  - stage: CD_to_production
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    variables:
      - group: production
    jobs:
      - deployment: production
        displayName: Deploy to production
        environment:
          name: production
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: CmdLine@2
                  inputs:
                    script: |
                      sudo apt update
                      sudo apt upgrade -y
                      sudo apt install docker.io -y
                      sudo chmod 666 /var/run/docker.sock
                - task: Docker@2
                  inputs:
                    containerRegistry: "weightapprepo.azurecr.io"
                    command: "login"

                - task: CmdLine@2
                  inputs:
                    script: |
                      docker rmi -f $(docker images -a -q)
                      docker rm -f $(docker ps -a -q)
                      docker pull weightapprepo.azurecr.io/weightapprepo:$(Build.BuildId)
                  displayName: clean and repull docker image

                - task: CmdLine@2
                  inputs:
                    script: |
                      docker run -d -p 8080:8080  --restart=always --name weightapp -e HOST=$(HOST) -e PORT=$(PORT) -e PGHOST=$(PGHOST) -e PGUSERNAME=$(PGUSERNAME) -e PGDATABASE=$(PGDBNAME) -e PGPASSWORD=$(PGPASS) -e COOKIE_ENCRYPT_PWD=$(COOKIE_ENCRYPT_PWD) -e OKTA_ORG_URL=$(OKTAURL) -e OKTA_CLIENT_ID=$(OKTACLIENT) -e OKTA_CLIENT_SECRET=$(OKTASECRET) weightapprepo.azurecr.io/weightapprepo:$(Build.BuildId)
                  displayName: docker run and restart
