trigger:
- main

pool:
  name: staging
  vmImage: "frontendMachine0"

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls'
- task: Docker@2
  inputs:
    containerRegistry: 'weightapprepo.azurecr.io'
    repository: 'weightapp'
    command: 'buildAndPush'
    Dockerfile: 'dockerfiles/Dockerfile'


