trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
variables:
  - group: staging
pool:
  name: Default
  vmImage: "terraformAgent"

stages:
# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
#    - template: setup.yml
    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here
          
          echo Hello world



# Continuous Deployment Process for Staging Environment
- stage: DeployToStaging
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: staging
    displayName: Deploy to Staging
    environment:
      name: staging
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
#          - template: setup.yml
          - task: CmdLine@2
            inputs:
              script: |
                echo Write your commands here
                
                echo Hello world