variables:
  - group: staging
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
pool:
  name: ubuntu
  vmImage: "terraformAgent"

stages:
# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
      - template: ci.yml



- stage: Deploy_to_Production
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
        - job: Deploy
          displayName: Deploy
        - deployment: VMDeploy
          displayName: web
          variables:
          - group: Production

          environment:
            name:  'Production' #ApprovalRequired
            resourceType: VirtualMachine
            tags: 'Production'
          strategy:
          # default deployment strategy
            runOnce:
              deploy:
                steps:
                - template: deploy.yml
