trigger:
  - main
  - feature/*

pool:
  vmImage: staging
  # vmImage: ubuntu-latest
stages:
  # Continuous Integration Process
  - stage: prepare_CI
    jobs:
      - deployment: staging
        displayName: Deploy to Staging
        environment:
          name: staging
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: CmdLine@2
                  inputs:
                    script: |
                      sudo apt update
                      sudo apt upgrade -y
                      sudo apt install docker.io -y
                      sudo chmod 666 /var/run/docker.sock
                - task: Docker@2
                  inputs:
                    containerRegistry: "weightapprepo.azurecr.io"
                    command: "login"

                - task: CmdLine@2
                  inputs:
                    script: |
                      docker rmi -f $(docker images -a -q)
                      docker rm -f $(docker ps -a -q)
                      docker pull weightapprepo.azurecr.io/weightapprepo:$(Build.BuildId)
                  displayName: clean and repull docker image

                - task: CmdLine@2
                  inputs:
                    script: |
                      docker run -d -p 8080:8080 --name weightapp weightapprepo.azurecr.io/weightapprepo:$(Build.BuildId)
                      cat .env
                  displayName: docker run and restart
