variables:
  - group: staging
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
pool:
  name: staging
  vmImage: "terraformAgent"

stages:
# Continuous Integration Process
- stage: CI
  jobs:
        - deployment: staging
          displayName: Deploy to Staging
          variables:
          - group: staging
          environment:
            name:  'staging' 
            resourceType: VirtualMachine
            tags: 'staging'
          strategy:
          # default deployment strategy
            runOnce:
              deploy:
                steps:
                - template: ci.yml

# Continuous Delivery Process
- stage: Deploy_to_Production
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
        - deployment: production
          displayName: Deploy to Production
          variables:
          - group: Production
          environment:
            name:  'Production' #ApprovalRequired
            resourceType: VirtualMachine
            tags: 'Production'
          strategy:
          # default deployment strategy
            runOnce:
              deploy:
                steps:
                - template: cd.yml
