---
- hosts: all
  become: true
  vars_files:
    - psecret.yml
  tasks:
    - name: update apt repositories
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: node14 setup
      shell: "curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs"
      args:
        warn: false

    - name: bring artifact to vms
      ansible.builtin.copy:
        src: /home/adminuser/ansible/psecret.yml
        dest: /home/adminuser/weightapp
        owner: root
        group: root
        mode: "0644"

    - name: bring artifact to vms
      ansible.builtin.copy:
        src: /home/adminuser/app.tar
        dest: /home/adminuser/
        owner: root
        group: root
        mode: "0644"

    - name: bring artifact to vms
      ansible.builtin.copy:
        src: /home/adminuser/app.tar
        dest: /home/adminuser/
        owner: root
        group: root
        mode: "0644"

    - name: build dir
      file:
        path: /home/adminuser/weightapp/
        state: directory

    - name: extract app.tar
      unarchive:
        src: /home/adminuser/app.tar
        dest: /home/adminuser/weightapp
        remote_src: true
        validate_certs: true

    - name: Create env file and populate it with vars
      copy:
        dest: "/home/adminuser/weightapp/.env"
        content: |
          PORT=8080
          HOST='0.0.0.0'
          HOST_URL= {{ HOST_URL }}
          COOKIE_ENCRYPT_PWD={{ COOKIE_ENCRYPT_PWD }}
          NODE_ENV={{ NODE_ENV }}
          PGHOST={{ PGHOST }}
          PGUSERNAME={{ PGUSERNAME }}
          PGDATABASE={{ PGDATABASE }}
          PGPASSWORD={{ PGPASSWORD }}
          PGPORT={{ PGPORT }}
          OKTA_ORG_URL={{ OKTA_ORG_URL }}
          OKTA_CLIENT_ID={{ OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET={{ OKTA_CLIENT_SECRET }}

    - name: make
      command: npm run initdb
      run_once: true
      args:
        chdir: /home/adminuser/weightapp

    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: clean old pm2
      shell: pm2 startup
      ignore_errors: yes

    - name: starting the state of pm2
      command: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u adminuser --hp /home/adminuser
      run_once: true
      args:
        chdir: /home/adminuser/weightapp

    - name: clean old pm2
      shell: pm2 delete all
      ignore_errors: yes

    - name: spawn app
      shell: pm2 start src/index.js
      args:
        chdir: /home/adminuser/weightapp/

    - name: saving the state of pm2
      shell: pm2 save
      args:
        chdir: /home/adminuser/weightapp/

    # - name: restart
    #   become: yes
    #   command: reboot
